export const CREATE_RUN_REQUEST = 'CREATE_RUN_REQUEST'
export const CREATE_RUN_ERROR = 'CREATE_RUN_ERROR'

export const UPDATE_RUN_REQUEST = 'UPDATE_RUN_REQUEST'
export const UPDATE_RUN_SUCCESS = 'UPDATE_RUN_SUCCESS'

export const GET_RUNS_REQUEST = 'GET_RUNS_REQUEST'
export const GET_RUNS_SUCCESS = 'GET_RUNS_SUCCESS'
export const GET_RUNS_ERROR = 'GET_RUNS_ERROR'

export const GET_RUN_BY_ID_REQUEST = 'GET_RUN_BY_ID_REQUEST'
export const GET_RUN_BY_ID_SUCCESS = 'GET_RUN_BY_ID_SUCCESS'

export const GET_RUNS_BY_USER_ID_REQUEST = 'GET_RUNS_BY_USER_ID_REQUEST'
export const GET_RUNS_BY_USER_ID_SUCCESS = 'GET_RUNS_BY_USER_ID_SUCCESS'

export const DELETE_RUN_REQUEST = 'DELETE_RUN_REQUEST'

export const RUN_SELECTED_IN_LIST = 'RUN_SELECTED_IN_LIST'
export const USER_RUNS_SELECTED_IN_LIST = 'USER_RUNS_SELECTED_IN_LIST'
export const RESET_USER_RUNS_SELECTED_IN_LIST = 'RESET_USER_RUNS_SELECTED_IN_LIST'

export const GENERIC_RUN_ERROR = 'GENERIC_RUN_ERROR'

export const RUNS_LIST_UNIT_OPTION = 'RUNS_LIST_UNIT_OPTION'

export const DONT_WANNA_WAIT = 'DONT_WANNA_WAIT'