export const LOAD_SIMPLE_TEST_DATA_REQUEST = 'LOAD_SIMPLE_TEST_DATA_REQUEST'
export const LOAD_SIMPLE_TEST_DATA_SUCCESS = 'LOAD_SIMPLE_TEST_DATA_SUCCESS'
export const LOAD_SIMPLE_TEST_DATA_FAILURE = 'LOAD_SIMPLE_TEST_DATA_FAILURE'
export const DONT_WANNA_WAIT = 'DONT_WANNA_WAIT'