export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST'

export const ERROR_USER_MESSAGE = 'ERROR_USER_MESSAGE'

export const USER_AUTHENTICATED_BY_TOKEN_FOUND = "USER_AUTHENTICATED_BY_TOKEN_FOUND"

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR'
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'

export const GET_USER_BY_ID_REQUEST = 'GET_USER_BY_ID_REQUEST'
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS'

export const GET_NAME_USER_RUNS_SUCESS = 'GET_NAME_USER_RUNS_SUCESS'

export const USER_SELECTED_IN_LIST = 'USER_SELECTED_IN_LIST'

export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_ERROR = 'GET_ALL_USERS_ERROR'

export const GET_TIMEZONES_REQUEST = 'GET_TIMEZONES_REQUEST'
export const GET_TIMEZONES_SUCCESS = 'GET_TIMEZONES_SUCCESS'

export const OPEN_PROFILE_REQUEST = 'OPEN_PROFILE_REQUEST'
export const OPEN_PROFILE_SUCCESS = 'OPEN_PROFILE_SUCCESS'

export const GET_USERS_BY_NAME_LIKE_REQUEST = 'GET_USERS_BY_NAME_LIKE_REQUEST'
export const GET_USERS_BY_NAME_LIKE_SUCCESS = 'GET_USERS_BY_NAME_LIKE_SUCCESS'

export const DONT_WANNA_WAIT = 'DONT_WANNA_WAIT'